FROM node:20-alpine AS builder

WORKDIR /app


COPY ../lib/types.ts ./lib/types.ts
COPY ../prisma ./prisma
COPY ../tsconfig.json ./tsconfig.json

RUN npm install ts-node typescript
RUN npm install prisma@6.6.0 --save-dev
RUN npm install date-fns
RUN npm install rrule
RUN npm install lucide-react

RUN npx prisma generate


FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app /app


