services:
  postgres:
    image: postgres:15
    container_name: container-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: meeting_room_scheduling
    ports:
      - "5432:5432"
    networks:
      - webnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  #prisma-migrate:
  #  build:
  #    context: ..
  #    dockerfile: container/Dockerfile.prisma-migrate
  #  environment:
  #    DATABASE_URL: ${DATABASE_URL}
  #    DATABASE_USER_USERNAME: ${DATABASE_USER_USERNAME}
  #  entrypoint: >
  #    sh -c "
  #      until  nc -z postgres 5432;
  #      do echo 'Waiting for Postgres...'; sleep 1; done;
  #      npx prisma migrate dev &&
  #      npx prisma db seed &&
  #      echo 'Migration complete.'"


  nextjs-app:
    build:
      context: ..
      dockerfile: container/Dockerfile.nextjs-app
    container_name: nextjs-app
    expose:
      - "3000"
    environment:
      BETTER_AUTH_URL: https://${DUCKDNS_DOMAIN}
      NEXTAPP_URL: https://${DUCKDNS_DOMAIN}
      # other env vars from .env
    depends_on:
      - postgres
    networks:
      - webnet
    extra_hosts:
      - "${DUCKDNS_DOMAIN}:host-gateway"
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:3000"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  nginx:
    build:
      context: ..
      dockerfile: container/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    environment:
      DUCKDNS_DOMAIN: ${DUCKDNS_DOMAIN}
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /etc/nginx/startup.sh
    depends_on:
      - nextjs-app #:
        #condition: service_healthy
    networks:
      - webnet
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
        


  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h;
      done"

  duckdns-updater:
    image: alpine:latest
    volumes:
      - ./duckdns:/scripts
    entrypoint: /bin/sh
    command: -c "while true; do sh /scripts/update.sh; sleep 300; done"

volumes:
  postgres_data:

networks:
  webnet: