import { PrismaClient } from "@prisma/client";
import { TColors } from "@/lib/types";
import { addDays, differenceInDays, endOfDay, startOfDay } from "date-fns";
import { EVENTDESCRIPTIONS, EVENTS, RECURRENCE_PATTERN, RECURRENCE_TYPE } from "./seed-data";
import { ByWeekday, datetime, RRule } from "rrule";

const prisma = new PrismaClient();

async function FindCreateAction(name: string) {
  let record = await prisma.action.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.action.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateRole(name: string) {
  let record = await prisma.role.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.role.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateResource(name: string) {
  let record = await prisma.resource.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.resource.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateRoleResourceAction(roleId: number, resourceId: number, actionId: number, permit: boolean) {
  let record = await prisma.roleResourceAction.findFirst({
    where: { roleId: roleId, resourceId: resourceId, actionId: actionId },
  });

  if (!record) {
    record = await prisma.roleResourceAction.create({
      data: { roleId: roleId, resourceId: resourceId, actionId: actionId, permit: permit },
    });
  }

  return record;
}

async function FindCreatePermissionSet(
  role: { roleId: number; createdAt: Date; updatedAt: Date; name: string },
  actions: {
    actionCreate: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionRead: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionUpdate: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionDelete: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
  },
  resource: { resourceId: number; createdAt: Date; updatedAt: Date; name: string },
  permissions: { create: boolean; read: boolean; update: boolean; delete: boolean }
) {
  const resourceActionEventCreate = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionCreate.actionId,
    permissions.create
  );
  const resourceActionEventRead = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionRead.actionId,
    permissions.read
  );
  const resourceActionEventUpdate = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionUpdate.actionId,
    permissions.update
  );
  const resourceActionEventDelete = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionDelete.actionId,
    permissions.delete
  );

  return { resourceActionEventCreate, resourceActionEventRead, resourceActionEventUpdate, resourceActionEventDelete };
}

async function FindCreateMember(userId: string, theme: string) {
  let record = await prisma.member.findFirst({
    where: { userId: userId },
  });

  if (!record) {
    record = await prisma.member.create({
      data: { userId: userId, theme: theme, timeFormat: "12hour" },
    });
  }

  return record;
}

async function FindCreateMemberRole(roleId: number, memberId: number) {
  let record = await prisma.memberRole.findFirst({
    where: { roleId: roleId, memberId: memberId },
  });

  if (!record) {
    record = await prisma.memberRole.create({
      data: { roleId: roleId, memberId: memberId },
    });
  }

  return record;
}

async function FindCreateRooms(name: string, color: TColors, icon: string) {
  let record = await prisma.room.findFirst({
    where: { name: name },
  });

  if (!record) {
    record = await prisma.room.create({
      data: { name: name, color: color, icon: icon },
    });
  }
  return record;
}

function FindRoomID(
  roomName: string,
  rooms: { name: string; createdAt: Date; updatedAt: Date; roomId: number; color: string; icon: string | null }[]
) {
  const test = rooms.find((room) => {
    return room.name === roomName;
  });

  return test?.roomId ?? 0;
}

function getRandomDescription(): string {
  const numberOfLines = Math.floor(Math.random() * EVENTDESCRIPTIONS.length);
  let newDescription = "";
  for (let index = 0; index <= numberOfLines; index++) {
    newDescription += EVENTDESCRIPTIONS[index] + "\n";
  }
  return newDescription;
}

// This was generated by AI -- minus the part where I added my wedding as an "easter egg" :)
async function CreateRandomEvents(
  rooms: {
    name: string;
    createdAt: Date;
    updatedAt: Date;
    roomId: number;
    color: string;
    icon: string | null;
  }[],
  maxEvents: number,
  maxRangeInDays: number = 30
) {
  // Date range: maxRangeInDays days before and after Now()
  const startRange = addDays(new Date(), maxRangeInDays);
  const endRange = addDays(new Date(), -maxRangeInDays);

  for (let index = 0; index < maxEvents; index++) {
    // Determine if this is a multi-day event (10% chance)
    const isMultiDay = Math.random() < 0.1;

    const startDate = new Date(startRange.getTime() + Math.random() * (endRange.getTime() - startRange.getTime()));

    // Set time between 8 AM and 8 PM
    startDate.setHours(8 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 4) * 15, 0, 0);

    const endDate = new Date(startDate);

    if (isMultiDay) {
      // Multi-day event: Add 1-12 days
      const additionalDays = Math.floor(Math.random() * 12) + 1;
      endDate.setDate(startDate.getDate() + additionalDays);

      endDate.setHours(8 + Math.floor(Math.random() * 12), Math.floor(Math.random() * 4) * 15, 0, 0);
    } else {
      const durationMinutes = (Math.floor(Math.random() * 11) + 2) * 15; // 30 to 180 minutes, multiple of 15
      endDate.setTime(endDate.getTime() + durationMinutes * 60 * 1000);
    }
    const eventIndex = Math.floor(Math.random() * EVENTS.length);

    await prisma.event.create({
      data: {
        roomId: rooms[Math.floor(Math.random() * rooms.length)].roomId,
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        title: EVENTS[eventIndex],
        description: getRandomDescription(),
        recurrenceId: await CreateRandomRecurrence(startDate, endDate),
      },
    });
  }
}

function randomToggle(chance: "75" | "50" | "25" | "10") {
  switch (chance) {
    case "75":
      return Math.random() < 0.75;
      break;
    case "50":
      return Math.random() < 0.5;
      break;
    case "25":
      return Math.random() < 0.25;
      break;
    case "10":
    default:
      return Math.random() < 0.1;
      break;
  }
}

async function CreateRandomRecurrence(startDate: Date, endDate: Date) {
  //IGNORE MULTI DAY EVENTS WE DONT WANT MULTI DAY RECURRING EVENTS
  if (differenceInDays(startOfDay(startDate), endOfDay(endDate)) > 1) {
    return undefined;
  }

  const TypeValue = RECURRENCE_TYPE[Math.floor(Math.random() * RECURRENCE_TYPE.length)];
  const PatternValue = RECURRENCE_PATTERN[Math.floor(Math.random() * RECURRENCE_PATTERN.length)];

  const occurrences = Math.floor(Math.random() * 100) + 1;

  let interval = 0;
  let dayValue = 0;
  let monthValue = 0;

  const maxPossibleDay: number[] = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

  const weekdayArray: ByWeekday[] = [];

  switch (PatternValue) {
    case "Every X Days":
      //PeriodValue = "Daily";
      interval = Math.floor(Math.random() * 7) + 1;
      break;
    case "Every Weekday":
      //PeriodValue = "Daily";
      interval = 1;
      weekdayArray.push(RRule.MO);
      weekdayArray.push(RRule.TU);
      weekdayArray.push(RRule.WE);
      weekdayArray.push(RRule.TH);
      weekdayArray.push(RRule.FR);
      break;
    case "Every X Weeks":
      //PeriodValue = "Weekly";
      interval = Math.floor(Math.random() * 7) + 1;
      break;
    case "Every X Weeks on Every Selected Day":
      //PeriodValue = "Weekly";
      interval = Math.floor(Math.random() * 7) + 1;

      if (randomToggle("25")) weekdayArray.push(RRule.MO);
      if (randomToggle("25")) weekdayArray.push(RRule.TU);
      if (randomToggle("25")) weekdayArray.push(RRule.WE);
      if (randomToggle("25")) weekdayArray.push(RRule.TH);
      if (randomToggle("25")) weekdayArray.push(RRule.FR);
      if (randomToggle("25")) weekdayArray.push(RRule.SA);
      if (randomToggle("25")) weekdayArray.push(RRule.SU);

      if (weekdayArray.length === 0) weekdayArray.push(RRule.TU);

      break;
    case "Every X Months on X Day":
      //PeriodValue = "Monthly";
      interval = Math.floor(Math.random() * 12) + 1;
      dayValue = Math.floor(Math.random() * 31) + 1;

      break;
    case "Every X Year on X Month on X Day":
      //PeriodValue = "Yearly";
      interval = Math.floor(Math.random() * 5) + 1;

      monthValue = Math.floor(Math.random() * 12) + 1;
      dayValue = Math.floor(Math.random() * maxPossibleDay[monthValue - 1]) + 1;

      break;
    default:
      //PeriodValue = "Daily";
      interval = Math.floor(Math.random() * 100) + 1;
      dayValue = Math.floor(Math.random() * 7) + 1;
      break;
  }

  const newStartDate = addDays(startDate, -Math.floor(Math.random() * 31));

  let newRule = undefined;

  if (TypeValue === "Occurrences") {
    switch (PatternValue) {
      case "Every X Days":
        newRule = new RRule({
          freq: RRule.DAILY,
          interval: interval,
          byweekday: weekdayArray,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          count: occurrences,
          until: null,
        });
        break;
      case "Every Weekday":
        newRule = new RRule({
          freq: RRule.DAILY,
          interval: interval,
          byweekday: weekdayArray,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          count: occurrences,
          until: null,
        });
        break;
      case "Every X Weeks":
        newRule = new RRule({
          freq: RRule.WEEKLY,
          interval: interval,
          byweekday: weekdayArray,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          count: occurrences,
          until: null,
        });
      case "Every X Weeks on Every Selected Day":
        newRule = new RRule({
          freq: RRule.WEEKLY,
          interval: interval,
          byweekday: weekdayArray,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          count: occurrences,
          until: null,
        });
        break;
      case "Every X Months on X Day":
        newRule = new RRule({
          freq: RRule.MONTHLY,
          interval: interval,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          bymonthday: dayValue,
          count: occurrences,
          until: null,
        });
        break;
      case "Every X Year on X Month on X Day":
        newRule = new RRule({
          freq: RRule.YEARLY,
          interval: interval,
          dtstart: datetime(
            newStartDate.getUTCFullYear(),
            newStartDate.getUTCMonth(),
            newStartDate.getUTCDate(),
            newStartDate.getUTCHours(),
            newStartDate.getUTCMinutes()
          ),
          bymonth: monthValue,
          bymonthday: dayValue,
          count: occurrences,
          until: null,
        });
        break;
    }
  } else if (TypeValue === "Between") {
  }

  if (!newRule) {
    return;
  }

  //console.log(newRule.all().at(-1));
  /*if (!newRule.all().at(-1)) {
    console.log(newRule);
    console.log(newRule.toString());
  }*/
  //let newEndDate = parseISO(newRule.all().at(-1)?.toISOString());

  const recurrence = await prisma.recurrence.create({
    data: {
      rule: newRule.toString(),
      startDate: newStartDate,
      endDate: newRule.all().at(-1) ?? "",
    },
  });

  return recurrence.recurrenceId;
}

async function main() {
  const actionCreate = await FindCreateAction("Create");
  const actionRead = await FindCreateAction("Read");
  const actionUpdate = await FindCreateAction("Update");
  const actionDelete = await FindCreateAction("Delete");

  const actions = { actionCreate, actionRead, actionUpdate, actionDelete };

  const roleUser = await FindCreateRole("User");
  const roleClerk = await FindCreateRole("Clerk");
  const roleAdmin = await FindCreateRole("Admin");

  const resourceEvent = await FindCreateResource("Event");

  const userPermissionSet = await FindCreatePermissionSet(roleUser, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const clerkPermissionSet = await FindCreatePermissionSet(roleClerk, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const adminPermissionSet = await FindCreatePermissionSet(roleAdmin, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const roomList: {
    name: string;
    createdAt: Date;
    updatedAt: Date;
    roomId: number;
    color: string;
    icon: string | null;
  }[] = [];

  //await FindCreateRooms("All", "zinc", "Asterisk");
  roomList.push(await FindCreateRooms("Algoma Board Room", "red", "BookKey"));
  roomList.push(await FindCreateRooms("Biggings Room", "orange", "BookKey"));
  roomList.push(await FindCreateRooms("Cafeteria", "amber", "BookKey"));
  roomList.push(await FindCreateRooms("Council Chambers", "indigo", "BookKey"));
  roomList.push(await FindCreateRooms("H.C. Hamilton Room", "lime", "BookKey"));
  roomList.push(await FindCreateRooms("Korah Room", "green", "BookKey"));
  roomList.push(await FindCreateRooms("Penthouse", "violet", "BookKey"));
  roomList.push(await FindCreateRooms("W.J. Thompson Room", "fuchsia", "BookKey"));
  roomList.push(await FindCreateRooms("Plummer Room", "cyan", "BookKey"));
  roomList.push(await FindCreateRooms("Steelton Room", "slate", "BookKey"));
  roomList.push(await FindCreateRooms("Tarentarus Room", "blue", "BookKey"));

  await prisma.event.deleteMany();
  await prisma.recurrence.deleteMany();

  CreateRandomEvents(roomList, 200);

  CreateRandomEvents(roomList, 2000, 1825);

  const user = await prisma.user.findFirst({ where: { email: "j.kahtava@cityssm.on.ca" } });
  if (!user) {
    return;
  }

  const member = await FindCreateMember(user?.id, "dark");

  const memberRole = FindCreateMemberRole(roleAdmin.roleId, member.memberId);

  /*
  const JordanKMember = await prisma.member.upsert({
    where: { userId: user?.id },
    update: {},
    create: { userId: user?.id, 
      theme: "dark",
      memberId: 1
     },
  });*/
  /*


  const alice = await prisma.user.upsert({
    where: { email: "alice@prisma.io" },
    update: {},
    create: {
      email: "alice@prisma.io",
      name: "Alice",
      posts: {
        create: {
          title: "Check out Prisma with Next.js",
          content: "https://www.prisma.io/nextjs",
          published: true,
        },
      },
    },
  });
  const bob = await prisma.user.upsert({
    where: { email: "bob@prisma.io" },
    update: {},
    create: {
      email: "bob@prisma.io",
      name: "Bob",
      posts: {
        create: [
          {
            title: "Follow Prisma on Twitter",
            content: "https://twitter.com/prisma",
            published: true,
          },
          {
            title: "Follow Nexus on Twitter",
            content: "https://twitter.com/nexusgql",
            published: true,
          },
        ],
      },
    },
  });*/
  //console.log({ alice, bob });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
