import { PrismaClient } from "@prisma/client";
import { TColors } from "@/components/calendar/lib/types";
import { addDays, addMonths, addWeeks, addYears, compareAsc, formatISO, isWeekend, parseISO, set } from "date-fns";
import { EVENTDESCRIPTIONS, EVENTS, RECURRENCE_PATTERN, RECURRENCE_PERIOD, RECURRENCE_TYPE } from "./seed-data";
import { start } from "repl";
import { first } from "lodash";

const prisma = new PrismaClient();

async function FindCreateAction(name: string) {
  let record = await prisma.action.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.action.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateRole(name: string) {
  let record = await prisma.role.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.role.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateResource(name: string) {
  let record = await prisma.resource.findFirst({ where: { name: name } });

  if (!record) {
    record = await prisma.resource.create({ data: { name: name } });
  }

  return record;
}

async function FindCreateRoleResourceAction(roleId: number, resourceId: number, actionId: number, permit: boolean) {
  let record = await prisma.roleResourceAction.findFirst({
    where: { roleId: roleId, resourceId: resourceId, actionId: actionId },
  });

  if (!record) {
    record = await prisma.roleResourceAction.create({
      data: { roleId: roleId, resourceId: resourceId, actionId: actionId, permit: permit },
    });
  }

  return record;
}

async function FindCreatePermissionSet(
  role: { roleId: number; createdAt: Date; updatedAt: Date; name: string },
  actions: {
    actionCreate: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionRead: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionUpdate: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
    actionDelete: { actionId: number; createdAt: Date; updatedAt: Date; name: string };
  },
  resource: { resourceId: number; createdAt: Date; updatedAt: Date; name: string },
  permissions: { create: boolean; read: boolean; update: boolean; delete: boolean }
) {
  const resourceActionEventCreate = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionCreate.actionId,
    permissions.create
  );
  const resourceActionEventRead = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionRead.actionId,
    permissions.read
  );
  const resourceActionEventUpdate = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionUpdate.actionId,
    permissions.update
  );
  const resourceActionEventDelete = await FindCreateRoleResourceAction(
    role.roleId,
    resource.resourceId,
    actions.actionDelete.actionId,
    permissions.delete
  );

  return { resourceActionEventCreate, resourceActionEventRead, resourceActionEventUpdate, resourceActionEventDelete };
}

async function FindCreateMember(userId: string, theme: string) {
  let record = await prisma.member.findFirst({
    where: { userId: userId },
  });

  if (!record) {
    record = await prisma.member.create({
      data: { userId: userId, theme: theme, timeFormat: "12hour" },
    });
  }

  return record;
}

async function FindCreateMemberRole(roleId: number, memberId: number) {
  let record = await prisma.memberRole.findFirst({
    where: { roleId: roleId, memberId: memberId },
  });

  if (!record) {
    record = await prisma.memberRole.create({
      data: { roleId: roleId, memberId: memberId },
    });
  }

  return record;
}

async function FindCreateRooms(name: string, color: TColors, icon: string) {
  let record = await prisma.room.findFirst({
    where: { name: name },
  });

  if (!record) {
    record = await prisma.room.create({
      data: { name: name, color: color, icon: icon },
    });
  }
  return record;
}

function FindRoomID(
  roomName: string,
  rooms: { name: string; createdAt: Date; updatedAt: Date; roomId: number; color: string; icon: string | null }[]
) {
  const test = rooms.find((room) => {
    return room.name === roomName;
  });

  return test?.roomId ?? 0;
}

function getRandomDescription(): string {
  const numberOfLines = Math.floor(Math.random() * EVENTDESCRIPTIONS.length);
  let newDescription = "";
  for (let index = 0; index <= numberOfLines; index++) {
    newDescription += EVENTDESCRIPTIONS[index] + "\n";
  }
  return newDescription;
}

// This was generated by AI -- minus the part where I added my wedding as an "easter egg" :)
async function CreateRandomEvents(
  rooms: {
    name: string;
    createdAt: Date;
    updatedAt: Date;
    roomId: number;
    color: string;
    icon: string | null;
  }[],
  maxEvents: number,
  maxRangeInDays: number = 30
) {
  // Date range: maxRangeInDays days before and after Now()
  const startRange = addDays(new Date(), maxRangeInDays);
  const endRange = addDays(new Date(), -maxRangeInDays);

  for (let index = 0; index < maxEvents; index++) {
    // Determine if this is a multi-day event (10% chance)
    const isMultiDay = Math.random() < 0.1;

    const startDate = new Date(startRange.getTime() + Math.random() * (endRange.getTime() - startRange.getTime()));

    // Set time between 8 AM and 8 PM
    startDate.setHours(8 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 4) * 15, 0, 0);

    const endDate = new Date(startDate);

    if (isMultiDay) {
      // Multi-day event: Add 1-12 days
      const additionalDays = Math.floor(Math.random() * 12) + 1;
      endDate.setDate(startDate.getDate() + additionalDays);

      endDate.setHours(8 + Math.floor(Math.random() * 12), Math.floor(Math.random() * 4) * 15, 0, 0);
    } else {
      const durationMinutes = (Math.floor(Math.random() * 11) + 2) * 15; // 30 to 180 minutes, multiple of 15
      endDate.setTime(endDate.getTime() + durationMinutes * 60 * 1000);
    }
    const eventIndex = Math.floor(Math.random() * EVENTS.length);

    const record = await prisma.event.create({
      data: {
        roomId: rooms[Math.floor(Math.random() * rooms.length)].roomId,
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        title: EVENTS[eventIndex],
        description: getRandomDescription(),
        recurrenceId: await CreateRandomRecurrence(startDate, endDate),
      },
    });
  }
}

async function CreateRandomRecurrence(startDate: Date, endDate: Date) {
  // Determine if this is a recurring event (10% chance)
  const isRecurringEvent = Math.random() < 0.1;

  if (!isRecurringEvent) {
    return undefined;
  }

  const TypeValue = RECURRENCE_TYPE[Math.floor(Math.random() * RECURRENCE_TYPE.length)];
  const PatternValue = RECURRENCE_PATTERN[Math.floor(Math.random() * RECURRENCE_PATTERN.length)];

  const occurrences = Math.floor(Math.random() * 100) + 1;

  let IsMonday = 0;
  let IsTuesday = 0;
  let IsWednesday = 0;
  let IsThursday = 0;
  let IsFriday = 0;
  let IsSaturday = 0;
  let IsSunday = 0;

  let daySpan = 0;
  let weekSpan = 0;
  let monthSpan = 0;
  let yearSpan = 0;

  let PeriodValue = "";

  switch (PatternValue) {
    case "Every X Days":
      PeriodValue = "Daily";
      daySpan = Math.floor(Math.random() * 7);
      break;
    case "Every Weekday":
      PeriodValue = "Daily";
      daySpan = 1;

      IsMonday = 1;
      IsTuesday = 1;
      IsWednesday = 1;
      IsThursday = 1;
      IsFriday = 1;
      IsSaturday = 0;
      IsSunday = 0;
      break;
    case "Every X Weeks":
      PeriodValue = "Weekly";
      weekSpan = Math.floor(Math.random() * 7) + 1;
      break;
    case "Every X Weeks on Every Selected Day":
      PeriodValue = "Weekly";
      weekSpan = Math.floor(Math.random() * 7) + 1;
      IsMonday = Math.floor(Math.random() * 1);
      IsTuesday = Math.floor(Math.random() * 1);
      IsWednesday = Math.floor(Math.random() * 1);
      IsThursday = Math.floor(Math.random() * 1);
      IsFriday = Math.floor(Math.random() * 1);
      IsSaturday = Math.floor(Math.random() * 1);
      IsSunday = Math.floor(Math.random() * 1);
      break;
    case "Every X Months on X Day":
      PeriodValue = "Monthly";
      daySpan = Math.floor(Math.random() * 31) + 1;
      monthSpan = Math.floor(Math.random() * 12);
      break;
    case "Every X Year on X Month on X Day":
      PeriodValue = "Yearly";
      daySpan = Math.floor(Math.random() * 31) + 1;
      monthSpan = Math.floor(Math.random() * 12);
      yearSpan = Math.floor(Math.random() * 5) + 1;
      break;
    default:
      PeriodValue = "Daily";
      daySpan = Math.floor(Math.random() * 7);
      break;
  }

  let newStartDate = addDays(startDate, -Math.floor(Math.random() * 31));
  let newEndDate = addDays(endDate, Math.floor(Math.random() * 31));

  if (TypeValue === "Forever") {
    newEndDate = parseISO("9999-12-31");
  } else if (TypeValue === "Occurrences") {
    let tempTotal = occurrences;
    let tempDate = newStartDate;
    switch (PatternValue) {
      case "Every X Days":
        tempDate = addDays(tempDate, daySpan * tempTotal);
        break;
      case "Every Weekday":
        for (let index = 1; index < tempTotal; index++) {
          //if the date is a weekend we need to get to the next weekday to increase the occurrence period
          while (isWeekend(tempDate)) {
            tempDate = addDays(tempDate, 1);
          }

          tempDate = addDays(tempDate, 1);
        }

        break;
      case "Every X Weeks":
      case "Every X Weeks on Every Selected Day":
        tempDate = addWeeks(tempDate, weekSpan * tempTotal);
        break;
      case "Every X Months on X Day":
        //Set the Date to the Month that we need
        //Then Add the Months to that Date 03-23 + 1 04-23

        //Take the current Month, change the Day so it matches the pattern.
        //Add the new Month Span to the current Month and Day that was set
        //This should give us the first recurrence.
        console.log(`\nSTART MONTH CALC  ${formatISO(tempDate, { representation: "date" })}`);
        console.log(occurrences, monthSpan, daySpan);
        let firstMonth = set(tempDate, { date: daySpan });

        if (compareAsc(tempDate, firstMonth) > 0) {
          console.log(
            `FIRST DATE ${formatISO(firstMonth, { representation: "date" })} LESS THEN CURRENT DATE ${formatISO(
              tempDate,
              { representation: "date" }
            )}`
          );
          console.log(`ADD ${monthSpan} MONTHS`);
          firstMonth = addMonths(firstMonth, monthSpan);
          tempTotal = tempTotal - 1;
        }
        console.log(`FIRST MONTH ${formatISO(firstMonth, { representation: "date" })}`);
        //once we found the first occurrence we can add all the others
        tempDate = addMonths(firstMonth, monthSpan * tempTotal);
        console.log(`CALCULATED DATE: ${formatISO(tempDate, { representation: "date" })}`);
        console.log("###END MONTH###");
        break;
      case "Every X Year on X Month on X Day":
        //OUTLOOK HAS AN INTERESTING BEHAVIOUR I WILL TRY AND MIMIC
        //IT SETS THE FIRST EVENT TO OCCUR IN THE SAME YEAR
        //SO IF THE RECURRENCE IS EVERY 3 YEARS IT WILL SET THE FIRST OCCURRENCE TO THIS YEAR.
        //2026-08-21, 1 Occurrence @ 3 Years, September, 19th = 2026-09-19
        //THEN EACH RECURRENCE IS CALCULATED BASED ON THIS VALUE 2026-09-19
        //IF THE START DATE WOULD HAPPEN AFTER THOUGH SO IF 2026-09-20 THEN IT BECOMES 2029-09-19
        console.log(`START YEAR CALC  ${tempDate}`);
        console.log(occurrences, yearSpan, monthSpan + 1, daySpan);
        let firstDate = set(tempDate, { month: monthSpan, date: daySpan });

        if (compareAsc(tempDate, firstDate) > 0) {
          console.log(`FIRST DATE ${firstDate} LESS THEN CURRENT DATE ${tempDate}`);
          console.log(`ADD ${yearSpan} YEARS`);
          firstDate = addYears(firstDate, yearSpan);
          tempTotal = tempTotal - 1;
        }

        console.log(`FIRST DATE ${firstDate}`);
        tempDate = addYears(firstDate, yearSpan * tempTotal);

        //const firstYear = addYears(set(tempDate, { month: monthSpan, date: daySpan }), yearSpan);
        //console.log(firstYear);

        //tempDate = addYears(firstYear, yearSpan * occurrences);
        console.log(`CALCULATED DATE: ${tempDate}`);
        console.log("###END YEAR###");
        //tempDate = set(tempDate, { month: monthSpan, date: daySpan });
        break;
    }
    newEndDate = tempDate;
  } else if (TypeValue === "Between") {
  }

  const recurrence = await prisma.recurrence.create({
    data: {
      type: TypeValue,
      pattern: PatternValue,
      totalOccurrences: occurrences,
      startDate: newStartDate,
      endDate: newEndDate,
      daySpan: daySpan,
      weekSpan: weekSpan,
      monthSpan: monthSpan,
      yearSpan: yearSpan,
      monday: IsMonday,
      tuesday: IsTuesday,
      wednesday: IsWednesday,
      thursday: IsThursday,
      friday: IsFriday,
      saturday: IsSaturday,
      sunday: IsSunday,
    },
  });

  return recurrence.recurrenceId;
}

async function main() {
  const actionCreate = await FindCreateAction("Create");
  const actionRead = await FindCreateAction("Read");
  const actionUpdate = await FindCreateAction("Update");
  const actionDelete = await FindCreateAction("Delete");

  const actions = { actionCreate, actionRead, actionUpdate, actionDelete };

  const roleUser = await FindCreateRole("User");
  const roleClerk = await FindCreateRole("Clerk");
  const roleAdmin = await FindCreateRole("Admin");

  const resourceEvent = await FindCreateResource("Event");

  const userPermissionSet = await FindCreatePermissionSet(roleUser, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const clerkPermissionSet = await FindCreatePermissionSet(roleClerk, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const adminPermissionSet = await FindCreatePermissionSet(roleAdmin, actions, resourceEvent, {
    create: false,
    read: true,
    update: false,
    delete: false,
  });

  const roomList: {
    name: string;
    createdAt: Date;
    updatedAt: Date;
    roomId: number;
    color: string;
    icon: string | null;
  }[] = [];

  //await FindCreateRooms("All", "zinc", "Asterisk");
  roomList.push(await FindCreateRooms("Algoma Board Room", "red", "BookKey"));
  roomList.push(await FindCreateRooms("Biggings Room", "orange", "BookKey"));
  roomList.push(await FindCreateRooms("Cafeteria", "amber", "BookKey"));
  roomList.push(await FindCreateRooms("Council Chambers", "indigo", "BookKey"));
  roomList.push(await FindCreateRooms("H.C. Hamilton Room", "lime", "BookKey"));
  roomList.push(await FindCreateRooms("Korah Room", "green", "BookKey"));
  roomList.push(await FindCreateRooms("Penthouse", "violet", "BookKey"));
  roomList.push(await FindCreateRooms("W.J. Thompson Room", "fuchsia", "BookKey"));
  roomList.push(await FindCreateRooms("Plummer Room", "cyan", "BookKey"));
  roomList.push(await FindCreateRooms("Steelton Room", "slate", "BookKey"));
  roomList.push(await FindCreateRooms("Tarentarus Room", "blue", "BookKey"));

  await prisma.event.deleteMany();
  await prisma.recurrence.deleteMany();

  CreateRandomEvents(roomList, 200);

  CreateRandomEvents(roomList, 2000, 1825);

  const user = await prisma.user.findFirst({ where: { email: "j.kahtava@cityssm.on.ca" } });
  if (!user) {
    return;
  }

  const member = await FindCreateMember(user?.id, "dark");

  const memberRole = FindCreateMemberRole(roleAdmin.roleId, member.memberId);

  /*
  const JordanKMember = await prisma.member.upsert({
    where: { userId: user?.id },
    update: {},
    create: { userId: user?.id, 
      theme: "dark",
      memberId: 1
     },
  });*/
  /*


  const alice = await prisma.user.upsert({
    where: { email: "alice@prisma.io" },
    update: {},
    create: {
      email: "alice@prisma.io",
      name: "Alice",
      posts: {
        create: {
          title: "Check out Prisma with Next.js",
          content: "https://www.prisma.io/nextjs",
          published: true,
        },
      },
    },
  });
  const bob = await prisma.user.upsert({
    where: { email: "bob@prisma.io" },
    update: {},
    create: {
      email: "bob@prisma.io",
      name: "Bob",
      posts: {
        create: [
          {
            title: "Follow Prisma on Twitter",
            content: "https://twitter.com/prisma",
            published: true,
          },
          {
            title: "Follow Nexus on Twitter",
            content: "https://twitter.com/nexusgql",
            published: true,
          },
        ],
      },
    },
  });*/
  //console.log({ alice, bob });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
