export const VISIBLE_HOUR_START = 0;
export const VISIBLE_HOUR_END = 24;
export const TIME_SLOT_INTERVAL_MINUTES = 15;

export const RECURRENCE_TYPE = ["Between", "Occurrences", "Forever"];

export const RECURRENCE_PERIOD = ["daily", "weekly", "monthly", "yearly"];

export const RECURRENCE_PATTERN = [
	"Every X Days",
	"Every Weekday",
	"Every X Weeks",
	"Every X Weeks on Every Selected Day",
	"Every X Months on X Day",
	"Every X Year on X Month on X Day",
];

export const EVENTS = [
	"Doctor's appointment",
	"Dental cleaning",
	"Eye exam",
	"Therapy session",
	"Business meeting",
	"Team stand-up",
	"Project deadline",
	"Weekly report submission",
	"Client presentation",
	"Marketing strategy review",
	"Networking event",
	"Sales call",
	"Investor pitch",
	"Board meeting",
	"Employee training",
	"Performance review",
	"One-on-one meeting",
	"Lunch with a colleague",
	"HR interview",
	"Conference call",
	"Web development sprint planning",
	"Software deployment",
	"Code review",
	"QA testing session",
	"Cybersecurity audit",
	"Server maintenance",
	"API integration update",
	"Data backup",
	"Cloud migration",
	"System upgrade",
	"Content planning session",
	"Product launch",
	"Customer support review",
	"Team building activity",
	"Legal consultation",
	"Budget review",
	"Financial planning session",
	"Tax filing deadline",
	"Investor relations update",
	"Partnership negotiation",
	"Medical check-up",
	"Vaccination appointment",
	"Blood donation",
	"Gym workout",
	"Yoga class",
	"Physical therapy session",
	"Nutrition consultation",
	"Personal trainer session",
	"Parent-teacher meeting",
	"School open house",
	"College application deadline",
	"Final exam",
	"Graduation ceremony",
	"Job interview",
	"Internship orientation",
	"Office relocation",
	"Business trip",
	"Flight departure",
	"Hotel check-in",
	"Vacation planning",
	"Birthday party",
	"Wedding anniversary",
	"Family reunion",
	"Housewarming party",
	"Community volunteer work",
	"Charity fundraiser",
	"Religious service",
	"Concert attendance",
	"Theater play",
	"Movie night",
	"Sporting event",
	"Football match",
	"Basketball game",
	"Tennis practice",
	"Marathon training",
	"Cycling event",
	"Fishing trip",
	"Camping weekend",
	"Hiking expedition",
	"Photography session",
	"Art workshop",
	"Cooking class",
	"Book club meeting",
	"Grocery shopping",
	"Car maintenance",
	"Home renovation meeting",
];

export const EVENTDESCRIPTIONS = [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	"Nulla mollis eget ipsum id tristique.",
	"Donec in orci in nisl bibendum fermentum.",
	"Donec ac enim risus.",
	"Fusce sagittis, magna id aliquam viverra, nibh dui posuere mauris, id malesuada libero libero sit amet sem.",
	"Suspendisse potenti.",
	"Donec ac ante nisi.",
	"Nulla a lobortis odio, eget condimentum nisl.",
	"Vivamus dictum, augue at vulputate eleifend, nisi mauris dignissim libero, faucibus vehicula tellus urna sed leo.",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	"Curabitur vitae posuere nibh, id accumsan ante.",
	"Suspendisse ac quam ipsum.",
	"Sed vestibulum tortor eget risus mattis, ut cursus est finibus.",
	"Aenean id felis vel erat porttitor pretium at non leo.",
	"Donec non odio lorem.",
	"Vestibulum mattis erat vel gravida interdum.",
	"Ut non porta orci.",
	"Integer efficitur magna at maximus faucibus.",
	"Donec hendrerit dolor vel nulla posuere, vitae rutrum metus suscipit.",
	"Fusce blandit elit quis risus sodales maximus.",
	"Phasellus placerat vulputate dui luctus facilisis.",
	"Nunc sed dignissim velit.",
	"Etiam non sapien lacus.",
	"Donec nec felis tincidunt, maximus ligula eu, tempor eros.",
	"Aenean non porttitor eros.",
	"Phasellus laoreet rutrum libero et iaculis.",
	"Praesent scelerisque, nisl eget venenatis suscipit, risus ante consectetur arcu, a cursus ipsum neque ut justo.",
	"Mauris enim tellus, mattis quis ultrices id, aliquet eget sem.",
	"Pellentesque eu mauris non odio ultricies gravida.",
	"Nam mi nisi, commodo vitae vulputate eget, convallis quis libero.",
	"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus eu augue imperdiet, convallis metus in, facilisis ante.",
	"Duis faucibus urna vel lacus cursus, dictum ullamcorper nunc iaculis.",
	"Donec vitae dolor quis odio semper euismod maximus vitae ex.",
	"In hac habitasse platea dictumst.",
	"Nulla ac auctor urna.",
	"Nullam purus metus, aliquam nec interdum quis, convallis ut purus.",
	"Phasellus nec posuere felis, sit amet sagittis est.",
	"Duis tincidunt tortor nec lectus tincidunt aliquam.",
	"Aliquam erat volutpat.",
	"Pellentesque sagittis, augue non facilisis bibendum, metus mauris blandit dolor, sed lobortis sem enim id lorem.",
	"Nulla porttitor ut velit nec malesuada.",
	"Suspendisse ut feugiat urna.",
	"Vestibulum maximus ut tortor eget lobortis.",
	"Sed ac cursus risus, non vehicula purus.",
	"Sed ex quam, hendrerit vel tincidunt ut, tincidunt a massa.",
	"Proin convallis efficitur purus sit amet dignissim.",
	"Pellentesque at eleifend mauris.",
	"Quisque et eros vitae mi sollicitudin molestie vel sed mi.",
	"Curabitur et facilisis dolor, id imperdiet ligula.",
	"Nulla id orci id lectus pulvinar porttitor et vitae lectus.",
	"Aenean convallis varius tortor vitae lobortis.",
	"Aenean ac eleifend quam.",
	"Sed non sem quis elit pellentesque porta a in risus.",
	"In hac habitasse platea dictumst.",
	"Integer volutpat est et lacus iaculis, id suscipit est semper.",
	"Cras mauris elit, dignissim vel risus quis, efficitur posuere velit",
	"Etiam ornare ullamcorper interdum",
];

export const FIRST_NAMES = [
	"James",
	"Mary",
	"Robert",
	"Patricia",
	"John",
	"Jennifer",
	"Michael",
	"Linda",
	"David",
	"Elizabeth",
	"William",
	"Barbara",
	"Richard",
	"Susan",
	"Joseph",
	"Jessica",
	"Thomas",
	"Sarah",
	"Christopher",
	"Karen",
	"Charles",
	"Lisa",
	"Daniel",
	"Nancy",
	"Matthew",
	"Betty",
	"Anthony",
	"Sandra",
	"Mark",
	"Margaret",
	"Donald",
	"Ashley",
	"Steven",
	"Kimberly",
	"Andrew",
	"Emily",
	"Paul",
	"Donna",
	"Joshua",
	"Michelle",
	"Kenneth",
	"Dorothy",
	"Kevin",
	"Carol",
	"Brian",
	"Amanda",
	"George",
	"Melissa",
	"Timothy",
	"Deborah",
];

export const LAST_NAMES = [
	"Smith",
	"Johnson",
	"Williams",
	"Brown",
	"Jones",
	"Garcia",
	"Miller",
	"Davis",
	"Rodriguez",
	"Martinez",
	"Hernandez",
	"Lopez",
	"Gonzales",
	"Wilson",
	"Anderson",
	"Thomas",
	"Taylor",
	"Moore",
	"Jackson",
	"Martin",
	"Lee",
	"Perez",
	"Thompson",
	"White",
	"Harris",
	"Sanchez",
	"Clark",
	"Ramirez",
	"Lewis",
	"Robinson",
	"Walker",
	"Young",
	"Allen",
	"King",
	"Wright",
	"Scott",
	"Torres",
	"Nguyen",
	"Hill",
	"Flores",
	"Green",
	"Adams",
	"Nelson",
	"Baker",
	"Hall",
	"Rivera",
	"Campbell",
	"Mitchell",
	"Carter",
	"Roberts",
];

export const DOMAINS = [
	"company.com",
	"test.io",
	"service.net",
	"enterprise.org",
	"startup.ai",
	"techflow.dev",
	"globalcorp.biz",
	"nexus.solutions",
	"pixel.studio",
	"data.systems",
	"cloud.works",
	"synergy.inc",
	"vanguard.co",
	"horizon.team",
	"summit.agency",
	"bridge.tech",
	"quantum.logic",
	"velocity.app",
	"infinity.design",
	"legacy.group",
	"innovation.hub",
	"frontier.space",
	"atlas.world",
	"omega.consulting",
	"alpha.lab",
	"prime.network",
	"core.platform",
	"stellar.digital",
	"vector.ops",
	"beacon.cloud",
];
